# Usar a imagem base do Element Web
FROM vectorim/element-web:v1.11.70



# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos de customização
COPY kioskCND.js kioskCND.css entrypoint.sh config.json ./

# Garantir que o script entrypoint seja executável e verificar sua presença
RUN chmod +x /app/entrypoint.sh && \
    ls -la /app/entrypoint.sh && \
    head -n 1 /app/entrypoint.sh

# Copiar config.json para o diretório de assets do Element Web
#RUN cp /app/config.json /usr/share/nginx/html/config.json

# Copiar configuração do Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Expor porta do Nginx
EXPOSE 80

# Usar o entrypoint script (com sh explícito para garantir)
ENTRYPOINT ["sh", "/app/entrypoint.sh"]

